version: '3.8'
services:
  wordpress:
    image: wordpress:6-php8.3-fpm-alpine
    restart: always
    hostname: wordpress
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: "*XalL*85Lon&Qwu7gRSp"
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: nuae15_
      WORDPRESS_DEBUG: "false"
      WP_REDIS_HOST: redis
      WP_REDIS_PORT: 6379
      WP_CACHE_KEY_SALT: unique-wp-salt-xyz987654
      WORDPRESS_CONFIG_EXTRA: "define('COMPRESS_CSS', true); define('COMPRESS_SCRIPTS', true); define('CONCATENATE_SCRIPTS', true); define('ENFORCE_GZIP', true); define('AUTOSAVE_INTERVAL', 120); define('WP_POST_REVISIONS', 10); define('MEDIA_TRASH', true); define('EMPTY_TRASH_DAYS', 30); define('IMAGE_EDIT_OVERWRITE', true); define('DISALLOW_FILE_EDIT', true);"
      PHP_MEMORY_LIMIT: 256M
      PHP_MAX_EXECUTION_TIME: 300
      PHP_UPLOAD_MAX_FILESIZE: 75M
      PHP_POST_MAX_SIZE: 75M
      OPCACHE_ENABLE: 1
      OPCACHE_MEMORY_CONSUMPTION: 128
      OPCACHE_MAX_ACCELERATED_FILES: 10000
      PHP_FPM_UPSTREAM: wordpress:9000
    volumes:
      - wordpress_data:/var/www/html
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9000"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - db
      - redis
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    restart: always
    environment:
      NGINX_WORKER_PROCESSES: auto
      NGINX_WORKER_CONNECTIONS: 1024
      NGINX_KEEPALIVE_TIMEOUT: 65
      NGINX_GZIP: "on"
      NGINX_GZIP_LEVEL: 5
      NGINX_FASTCGI_BUFFERS: "8 16k"
      NGINX_FASTCGI_BUFFER_SIZE: 32k
      NGINX_CONFIG: php
      NGINX_PROXY_UPSTREAM: localhost:8080
    volumes:
      - wordpress_data:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ssl:/etc/ssl:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`nerkhuae.com`) || Host(`www.nerkhuae.com`)"
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.tls.certresolver=letsencrypt"
      - "traefik.http.services.wordpress.loadbalancer.server.port=80"
    depends_on:
      wordpress:
        condition: service_healthy
    networks:
      - app_network

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: a@FDe&09^^%TJsxD2zcC
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: "*XalL*85Lon&Qwu7gRSp"
      MARIADB_AUTO_UPGRADE: 1
      MARIADB_MAX_CONNECTIONS: 150
      MARIADB_INNODB_BUFFER_POOL_SIZE: 4G
      MARIADB_INNODB_LOG_FILE_SIZE: 384M
      MARIADB_INNODB_IO_CAPACITY: 2000
      MARIADB_THREAD_CACHE_SIZE: 48
      MARIADB_TMP_TABLE_SIZE: 64M
      MARIADB_MAX_HEAP_TABLE_SIZE: 64M
      MARIADB_JOIN_BUFFER_SIZE: 4M
      MARIADB_SORT_BUFFER_SIZE: 6M
      MARIADB_READ_RND_BUFFER_SIZE: 2M
    command: --skip-name-resolve --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql  # init script برای grant
    networks:
      - app_network

  redis:
    image: redis:alpine
    restart: always
    environment:
      REDIS_PASSWORD: caA0I#enFCb0cLU8St*%
      REDIS_MAXMEMORY: 256mb
      REDIS_MAXMEMORY_POLICY: allkeys-lru
      REDIS_DATABASES: 16
      REDIS_SAVE: "900 1 300 10 60 10000"
    networks:
      - app_network

volumes:
  wordpress_data:
  db_data:

networks:
  app_network:
    driver: bridge
